# Generated by Django 2.1.5 on 2019-01-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateEarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_brutto', models.FloatField()),
                ('worked_years', models.FloatField()),
            ],
        ),
    ]
