# Generated by Django 2.1.5 on 2019-01-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstimateEarning',
            new_name='Earning',
        ),
    ]
