# Generated by Django 2.1.5 on 2019-01-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190118_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
